# Copyright (c) 2022 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: aspeed-zephyr-project

  remotes:
    - name: github
      url-base: https://github.com/AspeedTech-BMC

  projects:
    - name: zephyr
      remote: github
      revision: 1e4df2976ce294ca07ebcb48f9a0e34c9c7fb85a
      import:
        name-whitelist:
          - mcumgr
          - cmsis
          - mcuboot
          - mbedtls
    - name: cerberus
      remote: github
      revision: 51e55fa2c73f91a81629cefd081e049b5518d2f1
      path: middlewares/cerberus
    - name: mcuboot
      remote: github
      revision: a844bb3089999c37f2f89873a6c493b1b0dfbd7a
      path: bootloader/mcuboot
