# Copyright (c) 2022 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: aspeed-zephyr-project

  remotes:
    - name: gerrit
      url-base: ssh://gerrit.aspeed.com:29418
    - name: github
      url-base: https://github.com/AspeedTech-BMC

  projects:
    - name: zephyr
      remote: gerrit
      revision: 4e6167c406b473cb2a9ec2b9c78d00fdbf5316df
      import:
        name-whitelist:
          - mcumgr
          - cmsis
          - mcuboot
          - mbedtls
    - name: cerberus
      remote: gerrit
      revision: 703de8bfd56162dfff546bb586b28c23fd44b9d0
      path: middlewares/cerberus
    - name: mcuboot
      remote: gerrit
      revision: 08fb1a46db5e84b91f0eb34d7ae2faac8b53030f
      path: bootloader/mcuboot
