# Copyright (c) 2022 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: aspeed-zephyr-project

  remotes:
    - name: gerrit
      url-base: ssh://gerrit.aspeed.com:29418
    - name: github
      url-base: https://github.com/AspeedTech-BMC

  projects:
    - name: zephyr
      remote: gerrit
      revision: fe062f968737959eae60dda8685b216b1d185807
      import:
        name-whitelist:
          - mcumgr
          - cmsis
          - mcuboot
          - mbedtls
    - name: cerberus
      remote: gerrit
      revision: 797977bfa8c1adece243a59d74df7a1bdf3abae6
      path: middlewares/cerberus
    - name: mcuboot
      remote: gerrit
      revision: ce9bdf834557ee71b3ba87c32a16990f306ee8ee
      path: bootloader/mcuboot
