# Copyright (c) 2022 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: aspeed-zephyr-project

  remotes:
    - name: gerrit
      url-base: ssh://gerrit.aspeed.com:29418
    - name: github
      url-base: https://github.com/AspeedTech-BMC

  projects:
    - name: zephyr
      remote: gerrit
      revision: ed8dfafd48c6ca898ab1185900efb431d68107d6
      import:
        name-whitelist:
          - mcumgr
          - cmsis
          - mcuboot
          - mbedtls
    - name: cerberus
      remote: gerrit
      revision: 51e55fa2c73f91a81629cefd081e049b5518d2f1
      path: middlewares/cerberus
    - name: mcuboot
      remote: gerrit
      revision: 74c4d1c52fd51d07904b27a7aa9b2303e896a4e3
      path: bootloader/mcuboot
